# -*- coding: utf-8 -*-
"""TesteDeSoftware.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF_oNuIA-yfe7Vf6VnOOTRS6frDmQRne


"""Programa"""

usuarios = {"karl": "senha123",
    "ana": "senha456",
    "joao": "senha789"}

def login():
    print("=== Sistema de Login ===")

    username = input("Digite seu nome de usuário: ")

    if username in usuarios:
        password = input("Digite sua senha: ")

        if usuarios[username] == password:
            print("Login bem-sucedido! Bem-vindo(a),", username)
        else:
            print("Senha incorreta!")
    else:
        print("Usuário não encontrado!")

login()
